version: '3.8'
services:
  backend:
    build:
      context: .
    image: danishyousuf/backend-pipeline
    platform: linux/amd64
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - db
    deploy:
      replicas: 2

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crudapp
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
