name: CI/CD Pipeline for Dockerized CRUD App

on:
  push:
    branches:
      - main  # Trigger this on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main' branch

jobs:
  # Push updated backend image to Docker Hub
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - name: Generate .env file
      run: echo -e "DB_USER=postgres\nDB_PASSWORD=postgres\nDB_NAME=crudapp\nDB_HOST=db\nDB_PORT=5432" > .env
          
    - name: Login Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - name: Build the Docker image
      run: docker compose -f docker-compose.yml build 
    - name: Push to dockerhub
      run: docker compose -f docker-compose.yml push

  deploy:

    runs-on: self-hosted

    steps:
    # Step 1: Pull Docker images using docker compose (V2)
    - name: Pull Docker images
      run: sudo docker compose -f docker-compose.yml pull

    # Step 2: Remove old containers using docker compose (V2)
    - name: Remove old containers
      run: sudo docker compose -f docker-compose.yml down --remove-orphans || true

    # Step 3: Build and run containers using docker compose (V2)
    - name: Build and run Docker containers
      run: sudo docker compose -f docker-compose.yml up -d --build