name: CI/CD Pipeline for Dockerized CRUD App

on:
  push:
    branches:
      - main  # Trigger this on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate .env file
      run: echo -e "DB_USER=postgres\nDB_PASSWORD=postgres\nDB_NAME=crudapp\nDB_HOST=db\nDB_PORT=5432" > .env

    - name: Verify current working directory
      run: pwd  # Print the current directory to verify where you are

    - name: List files in the directory
      run: ls -la  # List all files to ensure .env is created

    - name: Upload .env file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: env-file
        path: .env

    - name: Login Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Build the Docker image
      run: docker compose -f docker-compose.yml build 

    - name: Push to dockerhub
      run: docker compose -f docker-compose.yml push

  deploy:
    runs-on: self-hosted
    needs: build  # Ensure that the build job runs before deploy

    steps:
    # Step 1: Checkout repository again (to ensure that docker-compose.yml is present)
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Download the .env file artifact
    - name: Download .env file
      uses: actions/download-artifact@v3
      with:
        name: env-file

    # Debugging Step: Check if .env file is downloaded
    - name: Verify .env file download (for debugging)
      run: cat .env  # This will print the contents of the .env file after download

    # Step 3: Verify current working directory (debugging)
    - name: List files in the directory
      run: ls -la

    # Step 4: Pull Docker images using docker compose (V2)
    - name: Pull Docker images
      run: sudo docker compose -f docker-compose.yml pull

    # Step 5: Remove old containers using docker compose (V2)
    - name: Remove old containers
      run: sudo docker compose -f docker-compose.yml down --remove-orphans || true

    # Step 6: Build and run containers using docker compose (V2)
    - name: Build and run Docker containers
      run: sudo docker compose -f docker-compose.yml up -d --build
