name: CI/CD Pipeline for Dockerized CRUD App

on:
  push:
    branches:
      - main  # Trigger this on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main' branch

jobs:
  # Push updated backend image to Docker Hub
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - name: Generate .env file
        run: 
          echo "DB_USER=postgres" > .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "DB_NAME=crudapp" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env
    - name: Login Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - name: Build the Docker image
      run: docker compose -f docker-compose.yml build 
    - name: Push to dockerhub
      run: docker compose -f docker-compose.yml push